if(NOT PROJECT_NAME STREQUAL "transcribe")
    return()
endif()
include_guard(GLOBAL)
# Some CMake/MSVC combinations decode Czech /showIncludes output using the
# wrong code page. Ninja then misses header dependencies and links stale ABI
# layouts. Probe in UTF-8, matching the compiler output used by this build.
if(MSVC AND CMAKE_GENERATOR MATCHES "Ninja")
    set(_vtd_probe "${CMAKE_CURRENT_BINARY_DIR}/vtd-include-probe")
    file(WRITE "${_vtd_probe}.h" "")
    file(WRITE "${_vtd_probe}.cpp" "#include \"vtd-include-probe.h\"\n")
    execute_process(
        COMMAND "${CMAKE_CXX_COMPILER}" /nologo /showIncludes /c
            "${_vtd_probe}.cpp" "/Fo${_vtd_probe}.obj"
        OUTPUT_VARIABLE _vtd_includes
        RESULT_VARIABLE _vtd_probe_result
        ENCODING UTF-8)
    if(_vtd_probe_result EQUAL 0)
        string(REGEX MATCH "[^\r\n]*: +[^\r\n]*vtd-include-probe.h" _vtd_include_line "${_vtd_includes}")
        string(REGEX MATCH "[^\r\n]*: +" _vtd_include_prefix "${_vtd_include_line}")
        if(_vtd_include_prefix)
            set(CMAKE_CL_SHOWINCLUDES_PREFIX "${_vtd_include_prefix}")
        endif()
    endif()
endif()
add_compile_options(/Gy /Gw)
function(vtd_add_bridge)
    # The exact Q8 kernel mirrors this pinned CPU backend's AVX2/FMA reduction.
    # Other architectures, dynamic backends and AVX512 keep upstream fp32.
    if(MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|x86_64)$"
       AND GGML_AVX2 AND NOT GGML_NATIVE AND NOT GGML_AVX512 AND NOT GGML_BACKEND_DL)
        target_sources(transcribe PRIVATE "${VTD_ROOT}/native/exact_matvec.cpp")
        target_include_directories(transcribe PRIVATE "${VTD_ROOT}/native")
        target_compile_definitions(transcribe PRIVATE VTD_EXACT_Q8_MATVEC)
        set_source_files_properties("${VTD_ROOT}/native/exact_matvec.cpp" PROPERTIES COMPILE_OPTIONS /arch:AVX2)
        if(TRANSCRIBE_BUILD_TESTS AND TRANSCRIBE_BUILD_REAL_MODEL_TESTS)
            add_executable(vtd-exact-matvec-test "${VTD_ROOT}/native/tests/exact_matvec.cpp")
            target_include_directories(vtd-exact-matvec-test PRIVATE "${VTD_ROOT}/native" "${CMAKE_SOURCE_DIR}/src")
            target_link_libraries(vtd-exact-matvec-test PRIVATE transcribe ggml)
            add_test(NAME vtd_exact_matvec COMMAND vtd-exact-matvec-test)
            set_tests_properties(vtd_exact_matvec PROPERTIES SKIP_RETURN_CODE 77)
        endif()
    endif()
    add_library(vtd-transcribe-bridge STATIC "${VTD_ROOT}/native/transcribe_bridge.cpp")
    target_link_libraries(vtd-transcribe-bridge PRIVATE transcribe)
    if(TRANSCRIBE_BUILD_TESTS)
        add_executable(vtd-allocator-memory-test "${VTD_ROOT}/native/tests/allocator_memory.c")
        target_include_directories(vtd-allocator-memory-test PRIVATE "${CMAKE_SOURCE_DIR}/ggml/src")
        target_link_libraries(vtd-allocator-memory-test PRIVATE ggml)
        add_test(NAME vtd_allocator_memory COMMAND vtd-allocator-memory-test)
        if(TRANSCRIBE_BUILD_REAL_MODEL_TESTS)
            add_executable(vtd-canary-memory-test "${VTD_ROOT}/native/tests/canary_memory.cpp")
            target_include_directories(vtd-canary-memory-test PRIVATE "${CMAKE_SOURCE_DIR}/src")
            target_link_libraries(vtd-canary-memory-test PRIVATE transcribe ggml)
            add_test(NAME vtd_canary_memory COMMAND vtd-canary-memory-test)
            set_tests_properties(vtd_canary_memory PROPERTIES SKIP_RETURN_CODE 77)
        endif()
        add_executable(vtd-positions-test "${VTD_ROOT}/native/tests/positions.cpp")
        target_include_directories(vtd-positions-test PRIVATE "${CMAKE_SOURCE_DIR}/src")
        target_link_libraries(vtd-positions-test PRIVATE transcribe ggml)
        add_test(NAME vtd_positions COMMAND vtd-positions-test)
        add_executable(vtd-scheduler-memory-test "${VTD_ROOT}/native/tests/scheduler_memory.cpp")
        target_include_directories(vtd-scheduler-memory-test PRIVATE "${CMAKE_SOURCE_DIR}/src")
        target_link_libraries(vtd-scheduler-memory-test PRIVATE transcribe ggml psapi)
        add_test(NAME vtd_scheduler_memory COMMAND vtd-scheduler-memory-test)
    endif()
endfunction()
cmake_language(DEFER CALL vtd_add_bridge)
