name: Build
on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: cargo check --locked
  windows:
    uses: ./.github/workflows/windows-package.yml
